name: eros_n
description: An unofficial nhentai app.

publish_to: 'none'
version: 1.0.3+3

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  pretty_dio_logger: ^1.2.0-beta-1
  dio_http_cache: ^0.3.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  collection: ^1.16.0
  logger: ^1.1.0
  path_provider: ^2.0.11
  intl: ^0.17.0
  dynamic_color: ^1.5.4
  english_words: ^4.0.0
  flutter_inappwebview: ^5.4.3+7
  http: ^0.13.5
  webview_flutter: ^3.0.4
  html: ^0.15.0
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  cached_network_image: ^3.1.0
  font_awesome_flutter: ^10.2.1
  flutter_cache_manager: ^3.1.1
  octo_image: ^1.0.2
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_hive_store: ^3.2.0
  flutter_list_view: ^1.1.18
  tuple: ^2.0.0
  waterfall_flow: ^3.0.2
  hooks_riverpod: ^1.0.4
  auto_route: ^5.0.1
  flutter_smart_dialog: ^4.5.5+2
  sliver_tools: ^0.2.6
  freezed_annotation: ^2.1.0
  json_annotation: ^4.3.0
  photo_view: ^0.14.0
  easy_image_viewer: ^1.1.0
  async_builder: ^1.3.1
  preload_page_view: ^0.1.6
  flutter_hooks: ^0.18.5+1
  webview_cef: ^0.0.6
  desktop_webview_window: ^0.1.6
  package_info: ^2.0.0
  url_launcher: ^6.0.3
  share: ^2.0.4
  copy_with_extension: ^4.0.0
  path: ^1.8.2
  archive: ^3.3.1

dev_dependencies:
  # flutter pub run apn_json2model
  apn_json2model: ^2.3.0
  # flutter pub run build_runner build --delete-conflicting-outputs
  # flutter pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.0.3
  json_serializable: ^6.0.1
  copy_with_extension_gen: ^4.0.0
  isar_generator: ^3.0.0
  auto_route_generator: ^5.0.2
  index_generator: ^3.3.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  # flutter pub run intl_utils:generate
  intl_utils: ^2.5.1

dependency_overrides:
  json_serializable: ^6.0.1


flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: L10n


# flutter pub run index_generator
index_generator:
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'
  indexes:
    - path: lib/component/models
      name: index
    - path: lib/common/parser
      name: parser